### ISSUE TITLE
Errors often occur during use

### ISSUE THREAD

**Issue by hmppt** [landing-ai/vision-agent#166]
Could not extract JSON from the given str
![image](https://github.com/user-attachments/assets/66675f6b-4138-4040-afdb-4cd2c6ccd504)

**Comment by dillonalaird** [comment]
Could you show me which version you are using? You can run `pip list | grep vision-agent` to find the version. This was an issue in older versions sometimes with the debugger when the response would get cutoff because it was too long. We made 2 changes, added a retry https://github.com/landing-ai/vision-agent/blob/main/vision_agent/agent/vision_agent.py#L406 and increased the max tokens https://github.com/landing-ai/vision-agent/blob/main/vision_agent/lmm/lmm.py#L87

**Comment by hmppt** [comment]
Of course, the version I'm using is 0.2.81. This version was installed directly by me using `pip install vision-agent`.

**Comment by dillonalaird** [comment]
Hmmm we've definitely had this issue before but I haven't seen it since we made the fixes I mentioned. I'm having some trouble reproducing it now (just ran your example in your other issue post). Do you feel like it's random or happens with certain types of prompts you use? The case you posted is interesting because it looks like the LLM responded with the string:

```
.
Function input:
```

And was parsed incorrectly, which is not the issue I mentioned above where the output JSON gets cut off.

**Comment by hmppt** [comment]
Is it possible that this problem is caused by the custom function returning an empty return value when running?

**Comment by dillonalaird** [comment]
I don't think so, because it's coming from the debugger here https://github.com/landing-ai/vision-agent/blob/main/vision_agent/agent/vision_agent.py#L406 which doesn't deal with the tools. Do you notice the error is always something strange like that string? Trying to think of how to reproduce it on my end

**Comment by hmppt** [comment]
I modified the prompt and custom tools, and now I don’t have this problem anymore. Thanks for the answer. :)

**Comment by hmppt** [comment]
> Hmmm we've definitely had this issue before but I haven't seen it since we made the fixes I mentioned. I'm having some trouble reproducing it now (just ran your example in your other issue post). Do you feel like it's random or happens with certain types of prompts you use? The case you posted is interesting because it looks like the LLM responded with the string:
> 
> ```
> .
> Function input:
> ```
> 
> And was parsed incorrectly, which is not the issue I mentioned above where the output JSON gets cut off.


I started having this problem again
![image](https://github.com/user-attachments/assets/84645934-e4d5-4ce7-bacb-8f725c00a744)

It shows that the error occurs here
![image](https://github.com/user-attachments/assets/61c743a0-56aa-405a-99a4-e3fd27c204b5)


This may be because the string it receives cannot be converted into json format (judging from the error report, it does not even have a '}')

**Comment by hmppt** [comment]
Also this is the first time I have encountered such a problem.
![image](https://github.com/user-attachments/assets/d51a3689-e838-4c34-93f4-d5b805a70f6f)

**Comment by shankar-vision-eng** [comment]
@dillonalaird - is this issue resolved ?

**Comment by dillonalaird** [comment]
Hey @hmppt could you give it another test? I've added several updates that should help:
- extract_json now pulls out JSON if it's surrounded by extra text https://github.com/landing-ai/vision-agent/blob/main/vision_agent/agent/agent_utils.py#L11
- was also getting some weird json decoding errors with extra newline characters https://github.com/landing-ai/vision-agent/blob/main/vision_agent/agent/agent_utils.py#L26
- extra loops if pick best plan does not succeed at first https://github.com/landing-ai/vision-agent/blob/main/vision_agent/agent/vision_agent_coder.py#L260
- extra loops if debugger does not succeed at first https://github.com/landing-ai/vision-agent/blob/main/vision_agent/agent/vision_agent_coder.py#L460
